CPP=g++
LEX=flex
YACC=bison
LD=g++

all:		komp

komp:		def.tab.o lex.yy.o
		$(CC) lex.yy.o def.tab.o -o komp -ll

lex.yy.o:	lex.yy.c
		$(CC) -c lex.yy.c

lex.yy.c:	scanner.l
		$(LEX) scanner.l

def.tab.o:	def.tab.cc
		$(CC) -c def.tab.cc

def.tab.cc:	def.yy
		$(YACC) -d def.yy

clean:
		rm *.o komp def.tab.cc lex.yy.c
